### ISSUE TITLE
Document ingestion workflow

### ISSUE THREAD

**Issue by dr-rodriguez** [SIMPLE-AstroDB/SIMPLE-db#11]
Provide some documentation of what users should do when adding/updating data to the database. We should use a typical git workflow with pull requests, but ask users to commit mainly just the contents of the `data` directory with the output JSON files, alongside any scripts.

**Comment by kelle** [comment]
This is something which @NiallWhiteford can help with!

**Comment by kelle** [comment]
As the workflow for ingesting data comes together, we should be writing and updating the guide as we go. It should include relevant functions, common obstacles, and recommended workflow.

- adding data tests
- One PR for scripts and another for data files

it will eventually include links to template scripts.

**Comment by kelle** [comment]
In order to get started working with SIMPLE and astrodbkit2 on your local machine, you should fork and clone both repos.

fork the repo to your personal account (click the fork button)
clone your fork of the repo to your local machine
More details here:
https://docs.github.com/en/github/getting-started-with-github/fork-a-repo

At the end of the day, when you type git remote -v
you should have an origin which points to your fork and an upstream which points back here.

**Comment by kelle** [comment]
This issue is TOO BIG.
