### ISSUE TITLE
How to handle reference entries with more than one papers

### ISSUE THREAD

**Issue by zjzhang42** [SIMPLE-AstroDB/SIMPLE-db#115]
We should consider how to handle the `reference` entires with more than 1 papers for the same object. For example, ULAS J141623.94+134836.3 was independently discovered by Burningham+2010 and Scholz+2010. In such case, do we want to (1) enable the `reference` column to accept both papers in the database? or (2) keep only one paper in the record and add the other (or both) in the `comments` column? or something else?

**Comment by kelle** [comment]
It's not ideal, but for the moment, we are using the Comments column for this scenario.  This should be noted in the docs.

**Comment by kelle** [comment]
We are also encountering this with the ingestion of the Manj19 spectra. Almost all of the data should have two references. The problem is that we need the references entry to be just one thing which is constrained by the Publications table. Maybe we could have a column for "Other references" which has one other ref or a list of other refs and is not constrained by the Publications table.

**Comment by zjzhang42** [comment]
I like the idea of adding an "Other references" which has **a list of other refs** (e.g., refs are separated by "/" or others) that is not constrained by the Publications table.

**Comment by kelle** [comment]
Columns added to Spectra and Sources table in PR #228

**Comment by kelle** [comment]
The other references listed are often related to data provenance. Here are some relevant documents to data provenance:
- [IVOA Provenance Data Model Version 1.0](https://github.com/SIMPLE-AstroDB/SIMPLE-db/files/7759683/REC-ProvenanceDM-1.0-20200411.pdf)
- [Practical_Provenance_in_Astronomy](https://github.com/SIMPLE-AstroDB/SIMPLE-db/files/7759684/Practical_Provenance_in_Astronomy.pdf). Proceedings from ADASS XXX, Jan 2021.
