### ISSUE TITLE
Adopt more ObsCore Standards for column names? 

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#353]
ObsCore Data Model 1.1 prescribes column names. Maybe we should consider adopting some of these, especially as we're thinking of the template database?  @dr-rodriguez , thoughts?  See Appendix B (p. 40-53) of [REC-ObsCore-v1.1-20170509.pdf](https://github.com/SIMPLE-AstroDB/SIMPLE-db/files/10983793/REC-ObsCore-v1.1-20170509.pdf). (Is this indeed the latest?)

Relevant column names
- `access_url` instead of `spectrum` and add `access_format`
- `target_name` instead of `source`
- `s_ra` and `s_dec` instead of `ra` and `dec`
- `bib_reference` instead of `bibcode`
- add `o_calib_status` to the spectra table to indicate normalized spectra.

**Comment by dr-rodriguez** [comment]
Some quick thoughts: 

- The ObsCore columns are ONLY needed for an ObsCore table/view; they don't need to be adopted elsewhere. We're not really offering our database through VO protocols, so while these are good, we don't have to adhere to them if it doesn't make sense for us or adds too much overhead. Just as a note, at MAST we have a view that renames columns to the ObsCore standard just for that view, rather than changing the tables themselves. 
- `spectrum` is used by astrodbkit to specify which is the column to use for transforming to a Spectrum1D object. It's not too difficult to change or supply new ones, though (see https://github.com/dr-rodriguez/AstrodbKit2/blob/main/astrodbkit2/astrodb.py#L111)
- The defaults for astrodbkit2 is to have `source` be the primary and foreign key; see https://github.com/dr-rodriguez/AstrodbKit2/blob/main/astrodbkit2/__init__.py I would like to keep those as that is short and more generic than `target_name`. You can always use a different one, but will need to supply it when you instantiate the `Database` class.
- I don't think the extra `s_` for ra/dec really add anything
- For `bib_reference`, does that means the Publications table will have `reference` and `bib_reference`?
- I don't think we need to add `access_format` or `o_calib_status`

**Comment by kelle** [comment]
I want us to build something that is as interoperable from the start with other relevant tools. And while we don't plan to integrate with other databases, I want it to be super easy for folks to "merge" two different databases made with astrodbtoolkit, which I think is the same goal as ObsCor, isn't it?

I also feel like some people have put a LOT of thought into these column names and why not take advantage of that work if it's "easy" for us to implement?

If there's one field I would be in favor of adding, it would be calib_status for spectra. Right now, there's no good way to indicate if a spectrum is flux calibrated or normalized. And we have a mix.

**Comment by kelle** [comment]
While I understand that it might require some changes to `astrodbkit`, using `Spectra.c.access_url` instead of `Spectra.c.spectrum` makes good sense to me. We aren't actually providing the spectrum, we're giving a URL. (This would also extend to any similar tables, like Images.)

And yeah, if we adopted `bib_reference` for the ADS Bibcode, we would indeed have `reference` as our shortname and also a `bib_reference`.  I feel meh about this.

**Comment by dr-rodriguez** [comment]
Remember that ObsCore is a model to describe observations and data products- our database is primarily for targets, not observations. We do have some data products (Spectra) but again, this is where views come into play since that is the logical place to rename columns after you join underlying tables. Rather than making sweeping database column changes, I would rather effort be spent on working out how to encode views.

That being said, the change for `access_url` is trivial and I have no problem with it. In fact, the way it's set up you can pass a list of columns so both spectrum and access_url can still be supported. If you wanted to add calib_status (and access_format) that's also not a problem, but note that calib_status is optional in the ObsCore and there are 3 or 4 versions of it.

Our cone search logic (see https://github.com/dr-rodriguez/AstrodbKit2/blob/main/astrodbkit2/astrodb.py#L600) uses ra/dec by default, so changing it to `s_ra`/`s_dec` would require users to manually set that. Again- the code supports users specifying custom columns but I think `ra` is far more common than `s_ra`. Plus, note that `s_ra` is meant to be the center of the observation, not necessarily the target location (frequently, but not always, the same).

**Comment by kelle** [comment]
Huh, I think it's super interesting that you think SIMPLE is primarily about targets and not data products and observations. I absolutely think it's about data and observations...organizing the data is one of my primary motivations and observation planning is an important use case. This might be worth discussing more and making sure we have a coherent description for us and for our users.

So basically what you're saying is that we can always add an ObsCore layer on top. Which is reassuring.

What do you think about the ObsCore names for instrument and facility? Which I want to change anyway? (See issue # - will add when not mobile.)

**Comment by dr-rodriguez** [comment]
I think `facility_name` and `instrument_name` are fine to change. Is the change just for the Telescopes and Instruments table as you describe in #207? Or are you thinking every time an instrument is mentioned? I'll note that there is no need for foreign keys to match the same name as the column they refer to so we have some options as to how much we change.

**Comment by kelle** [comment]
After lots of discussion, the only thing I think I only want to change `spectrum` to `access_url` in the `Spectrum` table.
(This change will impact astrodbkit2 - related issue dr-rodriguez/AstrodbKit2#57)
