### ISSUE TITLE
Nan vs None [Discussion]

### ISSUE THREAD

**Issue by kelle** [SIMPLE-AstroDB/SIMPLE-db#363]
I assumed that None was the best thing to use to indicate missing data. Googling (and @Ajb2307's data science partner) indicate that is not always the case!  (See the most popular answer to this [SO post](https://stackoverflow.com/questions/17534106/what-is-the-difference-between-nan-and-none).). Question: Does Astro and/or STScI have a stance on this?  @dr-rodriguez ?

**Comment by Ajb2307** [comment]
For missing Data Nan can be prefered as it can be inputted into a mathematical function while None cannot
<img width="718" alt="image" src="https://user-images.githubusercontent.com/67712811/229204140-226c65f3-01ed-4b86-8345-42a2680310ac.png">

**Comment by dr-rodriguez** [comment]
This is dependent of the programming language and how missing data is stored. Databases have a concept of NULL and that works across datatypes. As you can imagine, that sometimes has issues because np.nan is explicitly a float (ie, there is no nan integer). I will point out that pandas 2.0 is moving towards the Apache Arrow datatypes, that I believe handle missing data better than numpy. At the end of the day, we may be stuck with None as it is is a python object as opposed to float/string/int. What we pick for astrodbkit2 must be datatype independent.

**Comment by dr-rodriguez** [comment]
If you need to do math on a database result, I think it is up to the user to sanitize it and remove missing values.
