### ISSUE TITLE
[Discussion] What to do with photometric spectral types?

### ISSUE THREAD

**Issue by rothermichaustin** [SIMPLE-AstroDB/SIMPLE-db#534]
Roth24 has photometric spectral types. Should we ingest them, or ingest them but not "adopt" them? Related to #482

**Comment by jgizis** [comment]
I would vote no, because they are not spectral types. You have to measure a spectral type from a spectrum with sufficient resolution in an appropriate wavelength range.  Broadband Colors or Absolute magnitudes are correlated with spectral type but not the same thing.  I'd say these are predictions of spectral types not measurements of spectral types.  

If the magnitudes are in the database then one can use whatever relations one likes to estimate the things that haven't been measured, but to me they need to be kept distinct.  

(Similarly, I wouldn't place 1/(photometric distance estimate in parsecs) into a table of measured trigonometric parallaxes although I'd be happy to have it in a "best distance estimate" table, and I wouldn't put a predicted i-z color in from a J-K measurement.)

Just an opinion of course, it all depends on what the database is supposed to represent.

**Comment by kelle** [comment]
There is also a good discussion happening in the #simple-archive Slack channel.  One suggesstion from there which I really like is the idea to add a Photometric boolean column. If there is only one spectral type and its based on photometry, it can still be adopted, but it will have a `Photometric = True` flag.
