### ISSUE TITLE
Instrumentation Uniqueness

### ISSUE THREAD

**Issue by Will-Cooper** [SIMPLE-AstroDB/SIMPLE-db#99]
Instrument should not be primary key but telescope-instrument combo; to allow for duplicated instrument names (e.g. nirspec/ osiris)

**Comment by kelle** [comment]
I think this is what was implemented,
Correct, @dr-rodriguez ? If so, please close this issue.

**Comment by dr-rodriguez** [comment]
No, this is not implemented yet. The Instruments table just has the instrument name as primary key. 
Should be a straightforward update, but hasn't been done yet.

**Comment by kelle** [comment]
or maybe we want to add a description and/or reference to the Instruments table.

**Comment by kelle** [comment]
Need to think about this a bit more but the idea is to make the Instrument name unique. So NIRSPEC-Keck, NIRSPEC-JWST or something like that.

**Comment by Will-Cooper** [comment]
Can it not be a compound key using the two attributes: telescope and instrument?

**Comment by dr-rodriguez** [comment]
Yes, this should work and it would look similar to what we already have for Modes and PhotometryFilters

**Comment by kelle** [comment]
After visualizing the schema with Arjun, we discussed the idea of combining the Telescopes, Instruments, and Modes table into one table.  I don't see why not to do this.  If there's an instrument for which there are many relevant modes, it will have multiple entries.  This would reduce the number of reference tables and declutter the schema.

**Comment by dr-rodriguez** [comment]
There is a whole concept of data normalization for purposes of database creation; see for example: https://www.sqlshack.com/what-is-database-normalization-in-sql-server/   

The gist of it is you want more simple tables rather than combinations. Yes, combinations make some queries easier, but they make ingests harder. I think our flaw was in not realizing the name could be a primary key. Despite making it less readable, a unique integer should have been used, which means we could have rows like: 
```
1, NIRSPEC, ref1
2, NIRSPEC, ref2
3, etc, etc
```

That said, if you want a de-normalized table that combines instrument, telescope, and modes that's fine. In fact, we already have that- the *Modes* table is essentially a combination of Telescope, Instruments, and Modes.

The biggest challenge would probably be in writing the relationships between tables. 
We've done this with the _Spectra_ and _Modes_ table: https://github.com/SIMPLE-AstroDB/SIMPLE-db/blob/028785537f4f61ccdb27a069ff920c479584d1a5/simple/schema.py#L255
But note that since those 3 columns are part of a primary key, then **all** 3 columns must be present in tables that refer to them (eg, Photometry, Spectra, PhotometryFilters)- you can't just refer to 1 or 2 of them. Any time you want to refer to a telescope, for example, you _must_ also provide an instrument and mode if we move to using this form.

An alternative is to not store this in a reference table at all- just have the columns in the individual data tables be unrestrained and the users can list whatever instrument/telescope/mode they need, without worrying about whether they exist first in a reference table. We run the risk of having alternate spellings (eg, HST vs Hubble), but that can still happen if we don't manage the relationships properly.

**Comment by kelle** [comment]
I want it to be constrained name space to enable more accurate queries. (Eg, someone searched HST and misses the ones using Hubble.)

I am not as concerned with retrofitting the current schema as I am in making a decision for the template schema. 

I think we'll have to discuss this at co-working to figure out the best way to go.

**Comment by kelle** [comment]
I don't like the idea of three primary keys (Telescope-Instrument-Mode). Maybe we just combine instrument and mode into Instruments and keep Telescopes stand alone.

**Comment by kelle** [comment]
- Keep Telescopes stand-alone. 
- Add `comment` to Telescopes.
- Add 'modes' to Instruments.
- Delete Modes table.

**Comment by dr-rodriguez** [comment]
I noticed the _Telescopes_ table already has a `description` column added 3 months ago. 
It's possible you opened an older file when you were showing this with the sqlite browser.

**Comment by kelle** [comment]
Yes, that is likely. I need to build a new .db file locally. It's on my list.

**Comment by dr-rodriguez** [comment]
I noticed the _Instruments_ and _Telescopes_ JSON files did not have description, but the schema file specifies that- probably an oversight of whatever PR added them so that's could be why they're missing in a DB file.

One thing to clarify: is `mode` to be used as part of the primary key in the _Instruments_ table? My guess is yes, so that we can constrain it with specified values. This does require that mode be populated everywhere, in both _Instruments_ and _Spectra_ (and elsewhere).

**Comment by kelle** [comment]
I don't think mode needs to a primary key. We can test for duplicates with the tests rather than enforcing with the schema.

**Comment by dr-rodriguez** [comment]
After working yesterday to implement `mode` as part of the primary key I think we do need it. Without it present we can only have 1 row per instrument, so Spex+Prism and SpeX+SXD would just be a single row- SpeX. That would keep the table and foreign key relationships simpler, but it would argue for removing `mode` entirely from that table as it wouldn't be useful. We can still keep it as a free-string field in _Spectra_, though. 

At the moment (see #380), my implementation has `instrument` and `mode` as primary keys with `telescope` as a foreign key to the _Telescopes_ table. That means the `instrument+mode` must be unique in that table and anything referring to that table must include both of those fields.

**Comment by kelle** [comment]
Roger! I'm hoping to have time to look at all these PRs this afternoon.
